FROM node:22.22.2-alpine3.22 AS base

WORKDIR /app


FROM base AS installer-prod

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV COREPACK_INTEGRITY_KEYS=0

COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    corepack enable && \
    pnpm i --frozen-lockfile --prefer-offline --ignore-scripts --prod

FROM base AS builder

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV COREPACK_INTEGRITY_KEYS=0

COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    corepack enable && \
    pnpm i --frozen-lockfile --prefer-offline --ignore-scripts

COPY . .

RUN npm run build


FROM base AS runner

COPY --chown=node:node entrypoint.sh .

RUN chmod +x entrypoint.sh && \
    apk add --no-cache \
        tini=0.19.0-r3 \
        jemalloc=5.3.0-r6

ENV LD_PRELOAD=/usr/lib/libjemalloc.so

USER node

COPY --chown=node:node --from=installer-prod /app/node_modules node_modules
COPY --chown=node:node --from=builder /app/dist dist
COPY --chown=node:node --from=builder /app/prisma prisma
COPY --chown=node:node package.json .
COPY --chown=node:node prisma.config.ts .

ARG ARG_API_PORT
EXPOSE $ARG_API_PORT

ARG ARG_NODE_MEMORY
ENV NODE_OPTIONS=" \
    --max-old-space-size=${ARG_NODE_MEMORY} \
"

ENTRYPOINT ["/sbin/tini", "--", "./entrypoint.sh"]

CMD ["node", "dist/index.js"]

# "--optimize-for-size", "--no-allow-child-process",

# --no-allow-fs-write \
# "--allow-proto=delete"
